#!/usr/bin/env python
#
# fab_send
#    fab modules file send and configuration
#
# Neil Gershenfeld
# CBA MIT 9/16/11
#
# (c) Massachusetts Institute of Technology 2011
# Permission granted for experimental and personal use;
# license for commercial sale available from MIT.
#

#
# file type commands
#

commands = {
    '.rml': 'port=/dev/ttyUSB0; stty -F $port 9600 raw -echo crtscts; cat "$file" > $port',
    '.camm': 'printer=vinyl; lpr -P$printer "$file"',
    #'.camm': 'port=/dev/ttyUSB0; stty -F $port 9600 raw -echo crtscts; cat "$file" > $port',
    '.epi': 'printer=laser; lpr -P$printer "$file"',
    '.uni': 'port=/dev/lp0; cat "$file" > $port',
     '.ps': 'okular "$file"',
      '.g': 'gedit "$file"',
    '.sbp': 'gedit "$file"',
    '.ord': 'gedit "$file"',
   }

#
# imports
#

import sys,os

#
# command line
#

if (len(sys.argv) == 1):
   print "command line: fab_send [file]"
   print "   file = file to send"
   print "   file type commands:"
   print "      ",commands
   sys.exit()

#
# get command
#

filename = sys.argv[1]

filetype = os.path.splitext(filename)[-1]

if (not commands.has_key(filetype)):
   print "fab_send:",filetype,"not defined"
   sys.exit()

command = 'file="'+filename+'"; '+commands[filetype]

#
# execute
#

print command
os.system(command)

