#!/usr/bin/env python
#
# fab_send
#    send file to destination
#
# Neil Gershenfeld 7/11/14
# (c) Massachusetts Institute of Technology 2014
#
# This work may be reproduced, modified, distributed,
# performed, and displayed for any purpose, but must
# acknowledge the fab modules project. Copyright is
# retained and must be preserved. The work is provided
# as is; no warranty is provided, and users accept all 
# liability.
#

#
# file type commands
#

commands = {
     '.eps': 'inkscape "$file"',
     '.grb': 'gerbv "$file"',
     '.drl': 'gerbv "$file"',
     '.dxf': 'gedit "$file"',
     '.epi': 'printer=laser; lprm -P$printer -; lpr -P$printer "$file"',
     '.uni': 'port=/dev/lp0; cat "$file" > $port',
     '.stl': 'meshlab "$file"',
     '.ord': 'gedit "$file"',
     '.camm': 'printer=vinyl; lpr -P$printer "$file"',
     '.rml': 'port=/dev/ttyUSB0; rml_send_gui "$file" $port',
     'Roland_SRM-20': 'printer=Roland_SRM-20; lpr -P$printer "$file"',
     '.g': 'gedit "$file"',
     '.sbp': 'gedit "$file"',
     '.plt': 'gedit "$file"',
     '.oms': 'gedit "$file"',
     }

#
# imports
#

import sys,os

#
# command line
#

if (not ((len(sys.argv) == 2) or (len(sys.argv) == 3))):
   print "command line: fab_send file [machine]"
   print "   file = file to send"
   print "   machine = machine to send file to (optional, default file suffix)"
   print "   available types:"
   print "      ",commands
   sys.exit()

#
# get command
#

filename = sys.argv[1]

if (len(sys.argv) == 2):
   filetype = os.path.splitext(filename)[-1]
else:
   filetype = sys.argv[2]

if (not commands.has_key(filetype)):
   print "fab_send:",filetype,"not defined"
   sys.exit()

command = 'file="'+filename+'"; '+commands[filetype]

#
# execute
#

print command
os.system(command)

